### ISSUE TITLE
Napačni milijoni v imenovalniku

### ISSUE THREAD

**Issue by stefanb** [gregopet/zapis-slovenskih-stevil#1]
https://github.com/gregopet/zapis-slovenskih-stevil/blob/873126ffd89c20c5e9ad8b8ad0c978339c6fed1a/cela_stevila.json#L534-L535
Tole je tožilnik. Imenovalnik bi bil "tristo trije milijoni"

Izgubil sem (koga ali kaj?) tristo tri milijone in sedaj nekje na cesti ležijo (kdo ali kaj?) tristo trije milijoni.

https://svetovalnica.zrc-sazu.si/topic/2089/raba-števnikov

Ta isti problem se pojavlja tudi pri drugih imenovalnikih, npr:

https://github.com/gregopet/zapis-slovenskih-stevil/blob/873126ffd89c20c5e9ad8b8ad0c978339c6fed1a/cela_stevila.json#L510-L511
Pravilno: "trije milijoni"

https://github.com/gregopet/zapis-slovenskih-stevil/blob/873126ffd89c20c5e9ad8b8ad0c978339c6fed1a/cela_stevila.json#L542-L543
Pravilno: "tristo štirje milijoni"

itd...

**Comment by gregopet** [comment]
Najlepša hvala!
