### ISSUE TITLE
1803603801 orodnik

### ISSUE THREAD

**Issue by stefanb** [gregopet/zapis-slovenskih-stevil#3]
https://github.com/gregopet/zapis-slovenskih-stevil/blob/3004abf436afc077adf3ee4d0f04ddaba1a02cdb/cela_stevila.json#L596
ž: **z** milijardo osemsto **tremi** milijoni šeststo tri tisoč osemsto eno
m: **z** milijardo osemsto **tremi** milijoni šeststo tri tisoč osemsto enim
s: **z** milijardo osemsto **tremi** milijoni šeststo tri tisoč osemsto enim

**Comment by gregopet** [comment]
Oh, nekdo je bil površen, ko je odstranjeval velika števila iz datoteke :blush: 

Hvala!
